export const constants = {
  PORT: process.env.PORT || 3000,
  HOST_URL: process.env.HOST_URL || "http://localhost:7000",
  //   SERVICE_URL: process.env.SERVICE_URL || 'http://localhost:8080',
  ADMIN_UI_URL: process.env.ADMIN_UI_URL || "http://localhost:4000",
  USER_UI_URL: process.env.END_USER_URL || "http://localhost:4000",
  ADMIN_URL: process.env.ADMIN_URL || "http://localhost:4001",
  IS_PROD: process.env.NODE_ENV == "production",
  SESSION_SECRET: process.env.SESSION_SECRET,
  PUBLIC_PATH: "src/public",
  PROFILE_PATH: "src/public/profile",
  LOGO_URL: `${process.env.HOST_URL}/static/images/foxly_logo_blue.png`,
  EXPORT_IMAGE: `${process.env.HOST_URL}/static/images/export.png`,
  TEMPLATE_LOGO: `${process.env.HOST_URL}/static/images/csv.png`,
  DEMO_CSV: `${process.env.HOST_URL}/static/bulkUrl/demo.csv`,
  PROMO_CODE_STRING:
    "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  ADMIN_SECRET: process.env.ADMIN_SECRET,
  DEFAULT_TIMEZONE: "Asia/Kolkata", // 'Australia/Melbourne',
  DATE_FORMAT: "YYYY-MM-DD",
  BULK_URL_CSV_FILE: "src/public/bulkUrl",
};
