export const constants = {
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_FROM: process.env.SENDGRID_FROM,
  VERIFY_TEMPLATE_ID: process.env.VERIFY_TEMPLATE_ID,
  WELCOME_TEMPLATE_ID: process.env.WELCOME_TEMPLATE_ID,
  FORGET_TEMPLATE_ID: process.env.FORGET_TEMPLATE_ID,
  PACKAGE_TEMPLATE_ID: process.env.PACKAGE_TEMPLATE_ID,
};
